server:
  port: 9101
spring:
  application:
    name: eureka-client1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9100/eureka
#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
        MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
        OkToRetryOnAllOperations: false  #是否所有操作都重试