#http://localhost:9200/actuator/routes
#http://localhost:9200/actuator/routes/details
server:
  port: 9200
spring:
  application:
    name: eureka-zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9100/eureka
    registerWithEureka: false
    fetchRegistry: true
zuul:
  routes:
    eureka-zuul:
      serviceId: eureka-zuul
  prefix: /api
management:
  endpoints:
    web:
      exposure:
        #添加需要暴露出去的路径，"*"表示所有路径
        include: "*"
